# Generated by Django 5.0.3 on 2024-03-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
